var champs = ['Ahri','Akali','Alistar','Amumu','Anivia','Annie','Ashe','Blitzcrank','Brand','Caitlyn','Cassiopeia','Chogath','Corki','Darius','Diana','DrMundo','Draven','Elise','Evelynn','Ezreal','FiddleSticks','Fiora','Fizz','Galio','Gangplank','Garen','Gragas','Graves','Hecarim','Heimerdinger','Irelia','Janna','JarvanIV','Jax','Jayce','Karma','Karthus','Kassadin','Katarina','Kayle','Kennen','Khazix','KogMaw','Leblanc','LeeSin','Leona','Lulu','Lux','Malphite','Malzahar','Maokai','MasterYi','MissFortune','Mordekaiser','Morgana','Nami','Nasus','Nautilus','Nidalee','Nocturne','Nunu','Olaf','Orianna','Pantheon','Poppy','Rammus','Renekton','Rengar','Riven','Rumble','Ryze','Sejuani','Shaco','Shen','Shyvana','Singed','Sion','Sivir','Skarner','Sona','Soraka','Swain','Syndra','Talon','Taric','Teemo','Tristana','Trundle','Tryndamere','TwistedFate','Twitch','Udyr','Urgot','Varus','Vayne','Veigar','Vi','Viktor','Vladimir','Volibear','Warwick','MonkeyKing','Xerath','XinZhao','Yorick','Zed','Ziggs','Zilean','Zyra']; 
var strings = 

{
  "flash_itemShop_broker_btnBuy_buy": "BUY",
	"flash_itemShop_broker_btnSell_sell": "SELL",
	"flash_itemShop_broker_goldTitle": "Gold",
	"flash_itemShop_builds_buildTitle": "Builds Into:",
	"flash_itemShop_categories_Active": "Active",
	"flash_itemShop_categories_AllItems": "All Items",
	"flash_itemShop_categories_Armor": "Armor",
	"flash_itemShop_categories_ArmorPenetration": "Armor Penetration",
	"flash_itemShop_categories_Attack": "Attack",
	"flash_itemShop_categories_AttackSpeed": "Attack Speed",
	"flash_itemShop_categories_Aura": "Aura",
	"flash_itemShop_categories_back": "Back",
	"flash_itemShop_categories_Boots": "Boots",
	"flash_itemShop_categories_colloquialism_Active": ";",
	"flash_itemShop_categories_colloquialism_Armor": ";",
	"flash_itemShop_categories_colloquialism_ArmorPenetration": ";",
	"flash_itemShop_categories_colloquialism_Attack": ";",
	"flash_itemShop_categories_colloquialism_AttackSpeed": ";as",
	"flash_itemShop_categories_colloquialism_Aura": ";",
	"flash_itemShop_categories_colloquialism_Boots": ";",
	"flash_itemShop_categories_colloquialism_Consumable": ";",
	"flash_itemShop_categories_colloquialism_Consumables": ";",
	"flash_itemShop_categories_colloquialism_CooldownReduction": ";cdr",
	"flash_itemShop_categories_colloquialism_CriticalStrike": ";",
	"flash_itemShop_categories_colloquialism_Damage": ";",
	"flash_itemShop_categories_colloquialism_Defense": ";",
	"flash_itemShop_categories_colloquialism_GoldPer": ";",
	"flash_itemShop_categories_colloquialism_Health": ";",
	"flash_itemShop_categories_colloquialism_HealthRegen": ";",
	"flash_itemShop_categories_colloquialism_LifeSteal": ";lifesteal",
	"flash_itemShop_categories_colloquialism_Magic": ";",
	"flash_itemShop_categories_colloquialism_MagicPenetration": ";",
	"flash_itemShop_categories_colloquialism_Mana": ";",
	"flash_itemShop_categories_colloquialism_ManaRegen": ";",
	"flash_itemShop_categories_colloquialism_Movement": ";",
	"flash_itemShop_categories_colloquialism_NonbootsMovement": ";",
	"flash_itemShop_categories_colloquialism_Slow": ";",
	"flash_itemShop_categories_colloquialism_SpellBlock": ";mr",
	"flash_itemShop_categories_colloquialism_SpellDamage": ";ap",
	"flash_itemShop_categories_colloquialism_SpellVamp": ";spellvamp",
	"flash_itemShop_categories_colloquialism_Tenacity": ";",
	"flash_itemShop_categories_Consumable": "Consumables",
	"flash_itemShop_categories_Consumables": "Consumables",
	"flash_itemShop_categories_CooldownReduction": "Cooldown Reduction",
	"flash_itemShop_categories_CooldownReducton": "Cooldown Reduction",
	"flash_itemShop_categories_CriticalStrike": "Critical Strike",
	"flash_itemShop_categories_crumbHome": "HOME",
	"flash_itemShop_categories_Damage": "Damage",
	"flash_itemShop_categories_Defense": "Defense",
	"flash_itemShop_categories_GoldPer": "Gold Per",
	"flash_itemShop_categories_Health": "Health",
	"flash_itemShop_categories_HealthRegen": "Health Regen",
	"flash_itemShop_categories_Internal": "Internal",
	"flash_itemShop_categories_LifeSteal": "Life Steal",
	"flash_itemShop_categories_Magic": "Magic",
	"flash_itemShop_categories_MagicPenetration": "Magic Penetration",
	"flash_itemShop_categories_Mana": "Mana",
	"flash_itemShop_categories_ManaRegen": "Mana Regen",
	"flash_itemShop_categories_message0": "Welcome to the Item Shop.  Please select a category to start browsing through the items.",
	"flash_itemShop_categories_message1": "Please select a second category.",
	"flash_itemShop_categories_message2": "Select an item to view details.",
	"flash_itemShop_categories_Movement": "Movement",
	"flash_itemShop_categories_NonbootsMovement": "Other Movement Items",
	"flash_itemShop_categories_Slow": "Slow",
	"flash_itemShop_categories_SpellBlock": "Magic Resist",
	"flash_itemShop_categories_SpellDamage": "Ability Power",
	"flash_itemShop_categories_SpellVamp": "Spell Vamp",
	"flash_itemShop_categories_Tenacity": "Tenacity",
	"flash_itemShop_categories_tooltip_AllItems": "Resets all filters and lists all items by total gold cost.",
	"flash_itemShop_categories_tooltip_Armor": "Reduces incoming physical damage",
	"flash_itemShop_categories_tooltip_Attack": "Header Category<br \/>Improves basic attacks and physical spells",
	"flash_itemShop_categories_tooltip_AttackSpeed": "Increases the rate of basic attacks (to a limit of 2.5 per second)",
	"flash_itemShop_categories_tooltip_Boots": "Increases Movement Speed<br \/>Multiple boots will not provide speed gains.",
	"flash_itemShop_categories_tooltip_Consumable": "Can be used for temporary benefits",
	"flash_itemShop_categories_tooltip_CooldownReduction": "Increases how often you can cast spells (to a limit of 40% Cooldown Reduction)",
	"flash_itemShop_categories_tooltip_CriticalStrike": "Causes basic attacks to have a chance of doing 200% damage",
	"flash_itemShop_categories_tooltip_Damage": "Increase physical damage",
	"flash_itemShop_categories_tooltip_Defense": "Header Category<br \/>Improves survivability",
	"flash_itemShop_categories_tooltip_Health": "Increases maximum Health",
	"flash_itemShop_categories_tooltip_HealthRegen": "Increases how fast Health is recovered",
	"flash_itemShop_categories_tooltip_LifeSteal": "Causes basic attacks to heal the attacker",
	"flash_itemShop_categories_tooltip_Magic": "Header Category<br \/>Improves spells",
	"flash_itemShop_categories_tooltip_Mana": "Increases maximum Mana",
	"flash_itemShop_categories_tooltip_ManaRegen": "Increases how fast Mana is recovered",
	"flash_itemShop_categories_tooltip_Movement": "Increases Movement Speed",
	"flash_itemShop_categories_tooltip_NonbootsMovement": "Increases Movement Speed",
	"flash_itemShop_categories_tooltip_SpellBlock": "Reduces incoming magical damage",
	"flash_itemShop_categories_tooltip_SpellDamage": "Increases spell damage and effectiveness",
	"flash_itemShop_categories_tooltip_SpellVamp": "Causes spell damage dealt to heal the caster",
	"flash_itemShop_categories_tooltip_Tenacity": "Reduces the duration of stuns, slows, taunts, fears, silences, blinds, and immobilizes",
	"flash_itemShop_inventory_title": "INVENTORY",
	"flash_itemShop_recommended_consumables": "Consumables",
	"flash_itemShop_recommended_defensive": "Defensive Items",
	"flash_itemShop_recommended_essential": "Essential Items",
	"flash_itemShop_recommended_offensive": "Offensive Items",
	"flash_itemShop_recommended_starting": "Starting Items",
	"flash_itemShop_recommnededItems_recommend": "Recommended Items",
	"flash_itemShop_requireGraph_requiresTitle": "Requires:",
	"flash_itemShop_Special_Recipe_Large": "Special",
	"flash_itemShop_Special_Recipe_Small": "*",
	"flash_itemShop_tab_AllItems": "All Items",
	"flash_itemShop_tab_Recommended": "Recommended",
	"flash_itemShop_titleBar_title": "Item  Shop",
	"flash_itemShop_tooltip_cost": "Cost:",
	"flash_itemShop_tooltip_gridMode": "Displays all items in a smaller grid mode",
	"flash_itemShop_tooltip_listMode": "Displays all items in a larger list mode",
	"flash_itemShop_tooltip_OriginalCost": "Original Cost:",
	"flash_itemShop_tooltip_sellsfor": "Sells for:",
	"flash_itemShop_tooltip_SellsFor": "Sells for: ",
	"flash_itemShop_tooltip_upgradeCost": "Upgrade Cost:",
	"game_character_displayname_Ahri": "Ahri",
	"game_character_displayname_Akali": "Akali",
	"game_character_displayname_Alistar": "Alistar",
	"game_character_displayname_Amumu": "Amumu",
	"game_character_displayname_Anivia": "Anivia",
	"game_character_displayname_Annie": "Annie",
	"game_character_displayname_Ashe": "Ashe",
	"game_character_displayname_Blitzcrank": "Blitzcrank",
	"game_character_displayname_Brand": "Brand",
	"game_character_displayname_Caitlyn": "Caitlyn",
	"game_character_displayname_Cassiopeia": "Cassiopeia",
	"game_character_displayname_Chogath": "Cho'Gath",
	"game_character_displayname_Corki": "Corki",
	"game_character_displayname_Darius": "Darius",
	"game_character_displayname_Diana": "Diana",
	"game_character_displayname_Draven": "Draven",
	"game_character_displayname_DrMundo": "Dr. Mundo",
	"game_character_displayname_Elise": "Elise",
	"game_character_displayname_Evelynn": "Evelynn",
	"game_character_displayname_Ezreal": "Ezreal",
	"game_character_displayname_FiddleSticks": "Fiddlesticks",
	"game_character_displayname_Fiora": "Fiora",
	"game_character_displayname_Fizz": "Fizz",
	"game_character_displayname_Galio": "Galio",
	"game_character_displayname_Gangplank": "Gangplank",
	"game_character_displayname_Garen": "Garen",
	"game_character_displayname_Gragas": "Gragas",
	"game_character_displayname_Graves": "Graves",
	"game_character_displayname_Hecarim": "Hecarim",
	"game_character_displayname_Heimerdinger": "Heimerdinger",
	"game_character_displayname_Irelia": "Irelia",
	"game_character_displayname_Janna": "Janna",
	"game_character_displayname_JarvanIV": "Jarvan IV",
	"game_character_displayname_Jax": "Jax",
	"game_character_displayname_Jayce": "Jayce",
	"game_character_displayname_Karma": "Karma",
	"game_character_displayname_Karthus": "Karthus",
	"game_character_displayname_Kassadin": "Kassadin",
	"game_character_displayname_Katarina": "Katarina",
	"game_character_displayname_Kayle": "Kayle",
	"game_character_displayname_Kennen": "Kennen",
	"game_character_displayname_Khazix": "Kha'Zix",
	"game_character_displayname_KogMaw": "Kog'Maw",
	"game_character_displayname_Leblanc": "LeBlanc",
	"game_character_displayname_LeeSin": "Lee Sin",
	"game_character_displayname_Leona": "Leona",
	"game_character_displayname_Lulu": "Lulu",
	"game_character_displayname_Lux": "Lux",
	"game_character_displayname_Malphite": "Malphite",
	"game_character_displayname_Malzahar": "Malzahar",
	"game_character_displayname_Maokai": "Maokai",
	"game_character_displayname_MasterYi": "Master Yi",
	"game_character_displayname_MissFortune": "Miss Fortune",
	"game_character_displayname_MonkeyKing": "Wukong",
	"game_character_displayname_Mordekaiser": "Mordekaiser",
	"game_character_displayname_Morgana": "Morgana",
	"game_character_displayname_Nami": "Nami",
	"game_character_displayname_Nasus": "Nasus",
	"game_character_displayname_Nautilus": "Nautilus",
	"game_character_displayname_Nidalee": "Nidalee",
	"game_character_displayname_Nocturne": "Nocturne",
	"game_character_displayname_Nunu": "Nunu",
	"game_character_displayname_Olaf": "Olaf",
	"game_character_displayname_Orianna": "Orianna",
	"game_character_displayname_Pantheon": "Pantheon",
	"game_character_displayname_Poppy": "Poppy",
	"game_character_displayname_Rammus": "Rammus",
	"game_character_displayname_Renekton": "Renekton",
	"game_character_displayname_Rengar": "Rengar",
	"game_character_displayname_Riven": "Riven",
	"game_character_displayname_Rumble": "Rumble",
	"game_character_displayname_Ryze": "Ryze",
	"game_character_displayname_Sejuani": "Sejuani",
	"game_character_displayname_Shaco": "Shaco",
	"game_character_displayname_Shen": "Shen",
	"game_character_displayname_Shyvana": "Shyvana",
	"game_character_displayname_Singed": "Singed",
	"game_character_displayname_Sion": "Sion",
	"game_character_displayname_Sivir": "Sivir",
	"game_character_displayname_Skarner": "Skarner",
	"game_character_displayname_Sona": "Sona",
	"game_character_displayname_Soraka": "Soraka",
	"game_character_displayname_Swain": "Swain",
	"game_character_displayname_Syndra": "Syndra",
	"game_character_displayname_Talon": "Talon",
	"game_character_displayname_Taric": "Taric",
	"game_character_displayname_Teemo": "Teemo",
	"game_character_displayname_Tristana": "Tristana",
	"game_character_displayname_Trundle": "Trundle",
	"game_character_displayname_Tryndamere": "Tryndamere",
	"game_character_displayname_TwistedFate": "Twisted Fate",
	"game_character_displayname_Twitch": "Twitch",
	"game_character_displayname_Udyr": "Udyr",
	"game_character_displayname_Urgot": "Urgot",
	"game_character_displayname_Varus": "Varus",
	"game_character_displayname_Vayne": "Vayne",
	"game_character_displayname_Veigar": "Veigar",
	"game_character_displayname_Vi": "Vi",
	"game_character_displayname_Viktor": "Viktor",
	"game_character_displayname_Vladimir": "Vladimir",
	"game_character_displayname_Volibear": "Volibear",
	"game_character_displayname_Warwick": "Warwick",
	"game_character_displayname_Xerath": "Xerath",
	"game_character_displayname_XinZhao": "Xin Zhao",
	"game_character_displayname_Yorick": "Yorick",
	"game_character_displayname_Zed": "Zed",
	"game_character_displayname_Ziggs": "Ziggs",
	"game_character_displayname_Zilean": "Zilean",
	"game_character_displayname_Zyra": "Zyra",
	"game_item_colloquialism_1001": ";",
	"game_item_colloquialism_1004": ";",
	"game_item_colloquialism_1005": ";",
	"game_item_colloquialism_1006": ";",
	"game_item_colloquialism_1007": ";",
	"game_item_colloquialism_1011": ";",
	"game_item_colloquialism_1018": ";",
	"game_item_colloquialism_1026": ";",
	"game_item_colloquialism_1027": ";",
	"game_item_colloquialism_1028": ";",
	"game_item_colloquialism_1029": ";",
	"game_item_colloquialism_1031": ";",
	"game_item_colloquialism_1033": ";",
	"game_item_colloquialism_1036": ";",
	"game_item_colloquialism_1037": ";",
	"game_item_colloquialism_1038": ";bf",
	"game_item_colloquialism_1042": ";",
	"game_item_colloquialism_1043": ";",
	"game_item_colloquialism_1051": ";",
	"game_item_colloquialism_1052": ";amptome",
	"game_item_colloquialism_1053": ";",
	"game_item_colloquialism_1054": ";",
	"game_item_colloquialism_1055": ";",
	"game_item_colloquialism_1056": ";",
	"game_item_colloquialism_1057": ";",
	"game_item_colloquialism_1058": ";",
	"game_item_colloquialism_1062": ";",
	"game_item_colloquialism_1063": ";",
	"game_item_colloquialism_2003": ";",
	"game_item_colloquialism_2004": ";",
	"game_item_colloquialism_2037": ";",
	"game_item_colloquialism_2038": ";",
	"game_item_colloquialism_2039": ";",
	"game_item_colloquialism_2041": ";",
	"game_item_colloquialism_2042": ";",
	"game_item_colloquialism_2043": ";",
	"game_item_colloquialism_2044": ";",
	"game_item_colloquialism_2047": ";",
	"game_item_colloquialism_3001": ";",
	"game_item_colloquialism_3003": ";",
	"game_item_colloquialism_3004": ";",
	"game_item_colloquialism_3005": ";",
	"game_item_colloquialism_3006": ";",
	"game_item_colloquialism_3009": ";",
	"game_item_colloquialism_3010": ";",
	"game_item_colloquialism_3020": ";",
	"game_item_colloquialism_3022": ";fm",
	"game_item_colloquialism_3024": ";",
	"game_item_colloquialism_3026": ";ga",
	"game_item_colloquialism_3027": ";roa",
	"game_item_colloquialism_3028": ";",
	"game_item_colloquialism_3031": ";ie",
	"game_item_colloquialism_3035": ";lw",
	"game_item_colloquialism_3037": ";",
	"game_item_colloquialism_3041": ";",
	"game_item_colloquialism_3044": ";",
	"game_item_colloquialism_3046": ";pd",
	"game_item_colloquialism_3047": ";",
	"game_item_colloquialism_3050": ";starks",
	"game_item_colloquialism_3057": ";",
	"game_item_colloquialism_3065": ";sv",
	"game_item_colloquialism_3067": ";",
	"game_item_colloquialism_3068": ";",
	"game_item_colloquialism_3069": ";",
	"game_item_colloquialism_3070": ";",
	"game_item_colloquialism_3071": ";bc",
	"game_item_colloquialism_3072": ";bt",
	"game_item_colloquialism_3075": ";",
	"game_item_colloquialism_3077": ";",
	"game_item_colloquialism_3078": ";triforce;tons of damage",
	"game_item_colloquialism_3082": ";",
	"game_item_colloquialism_3083": ";",
	"game_item_colloquialism_3084": ";",
	"game_item_colloquialism_3086": ";",
	"game_item_colloquialism_3089": ";",
	"game_item_colloquialism_3090": ";",
	"game_item_colloquialism_3091": ";",
	"game_item_colloquialism_3093": ";",
	"game_item_colloquialism_3096": ";",
	"game_item_colloquialism_3097": ";",
	"game_item_colloquialism_3098": ";",
	"game_item_colloquialism_3099": ";",
	"game_item_colloquialism_3100": ";",
	"game_item_colloquialism_3101": ";",
	"game_item_colloquialism_3102": ";bv",
	"game_item_colloquialism_3105": ";",
	"game_item_colloquialism_3106": ";",
	"game_item_colloquialism_3108": ";",
	"game_item_colloquialism_3109": ";",
	"game_item_colloquialism_3110": ";fh",
	"game_item_colloquialism_3111": ";",
	"game_item_colloquialism_3114": ";",
	"game_item_colloquialism_3115": ";",
	"game_item_colloquialism_3116": ";",
	"game_item_colloquialism_3117": ";",
	"game_item_colloquialism_3122": ";",
	"game_item_colloquialism_3123": ";",
	"game_item_colloquialism_3124": ";",
	"game_item_colloquialism_3126": ";",
	"game_item_colloquialism_3128": ";dfg",
	"game_item_colloquialism_3131": ";",
	"game_item_colloquialism_3132": ";",
	"game_item_colloquialism_3134": ";",
	"game_item_colloquialism_3135": ";",
	"game_item_colloquialism_3136": ";",
	"game_item_colloquialism_3138": ";",
	"game_item_colloquialism_3140": ";qss",
	"game_item_colloquialism_3141": ";sota",
	"game_item_colloquialism_3142": ";",
	"game_item_colloquialism_3143": ";",
	"game_item_colloquialism_3144": ";",
	"game_item_colloquialism_3145": ";",
	"game_item_colloquialism_3146": ";",
	"game_item_colloquialism_3152": ";wota",
	"game_item_colloquialism_3153": ";",
	"game_item_colloquialism_3154": ";",
	"game_item_colloquialism_3155": ";",
	"game_item_colloquialism_3156": ";",
	"game_item_colloquialism_3157": ";",
	"game_item_colloquialism_3158": ";",
	"game_item_colloquialism_3159": ";",
	"game_item_colloquialism_3161": ";",
	"game_item_colloquialism_3165": ";",
	"game_item_colloquialism_3166": ";",
	"game_item_colloquialism_3167": ";",
	"game_item_colloquialism_3168": ";",
	"game_item_colloquialism_3169": ";",
	"game_item_colloquialism_3170": ";",
	"game_item_colloquialism_3171": ";",
	"game_item_colloquialism_3172": ";",
	"game_item_colloquialism_3173": ";",
	"game_item_colloquialism_3174": ";",
	"game_item_colloquialism_3178": ";",
	"game_item_colloquialism_3180": ";",
	"game_item_colloquialism_3181": ";",
	"game_item_colloquialism_3183": ";",
	"game_item_colloquialism_3184": ";",
	"game_item_colloquialism_3185": ";",
	"game_item_colloquialism_3186": ";",
	"game_item_colloquialism_3187": ";",
	"game_item_colloquialism_3188": ";",
	"game_item_colloquialism_3190": ";",
	"game_item_colloquialism_3193": ";viktor",
	"game_item_colloquialism_3194": ";viktor",
	"game_item_colloquialism_3195": ";viktor",
	"game_item_colloquialism_3196": ";viktor",
	"game_item_colloquialism_3197": ";viktor",
	"game_item_colloquialism_3198": ";viktor",
	"game_item_colloquialism_3200": ";viktor",
	"game_item_description_1001": "<unique>UNIQUE Passive - Enhanced Movement:<\/unique> +25 Movement Speed<br><br><i><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i><\/i>",
	"game_item_description_1004": "<stats>+3 Mana Regen per 5 seconds<\/stats>",
	"game_item_description_1005": "<stats>+7 Mana Regen per 5 seconds<\/stats>",
	"game_item_description_1006": "<stats>+5 Health Regen per 5 seconds<\/stats>",
	"game_item_description_1007": "<stats>+15 Health Regen per 5 seconds<\/stats>",
	"game_item_description_1011": "<stats>+400 Health<\/stats>",
	"game_item_description_1018": "<stats>+15% Critical Strike Chance<\/stats>",
	"game_item_description_1026": "<stats>+40 Ability Power<\/stats>",
	"game_item_description_1027": "<stats>+200 Mana<\/stats>",
	"game_item_description_1028": "<stats>+180 Health<\/stats>",
	"game_item_description_1029": "<stats>+15 Armor<\/stats>",
	"game_item_description_1031": "<stats>+40 Armor<\/stats>",
	"game_item_description_1033": "<stats>+20 Magic Resist<\/stats>",
	"game_item_description_1036": "<stats>+10 Attack Damage<\/stats>",
	"game_item_description_1037": "<stats>+25 Attack Damage<\/stats>",
	"game_item_description_1038": "<stats>+45 Attack Damage<\/stats>",
	"game_item_description_1039": "<unique>UNIQUE Passive - Butcher:<\/unique> Damage dealt to monsters increased by 10%.<br><unique>UNIQUE Passive - Rend:<\/unique> Basic attacks deal 10 bonus true damage to monsters.<br><br><i><i><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i><\/i><\/i>",
	"game_item_description_1042": "<stats>+12% Attack Speed<\/stats>",
	"game_item_description_1043": "<stats>+30% Attack Speed<\/stats>",
	"game_item_description_1051": "<stats>+8% Critical Strike Chance<\/stats>",
	"game_item_description_1052": "<stats>+20 Ability Power<\/stats>",
	"game_item_description_1053": "<stats>+10 Attack Damage<br>+10% Life Steal<\/stats>",
	"game_item_description_1054": "<stats>+100 Health<br>+5 Armor<br>+5 Health Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Blocks 6 damage from champion basic attacks.",
	"game_item_description_1055": "<stats>+80 Health<br>+10 Attack Damage<\/stats><br><br><passive>Passive:<\/passive> Your basic attacks restore 5 health each time they hit an enemy.",
	"game_item_description_1056": "<stats>+80 Health<br>+15 Ability Power<br>+3 Mana Regen per 5 seconds<\/stats><br><br><passive>Passive:<\/passive> Restores 5 Mana when you kill an enemy unit.",
	"game_item_description_1057": "<stats>+45 Magic Resist<\/stats>",
	"game_item_description_1058": "<stats>+80 Ability Power<\/stats>",
	"game_item_description_1062": "<stats>+20 Attack Damage<br>+5% Life Steal<\/stats><br><br><unique>UNIQUE Passive - Prospector:<\/unique> +200 Health<br><br><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_1063": "<stats>+40 Ability Power<br>+10 Mana Regeneration<\/stats><br><br><unique>UNIQUE Passive - Prospector:<\/unique> +200 Health<br><br><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_1080": "<stats>+14 Health Regen per 5 seconds<br>+7 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Butcher:<\/unique> Damage dealt to monsters increased by 20%.<br><unique>UNIQUE Passive - Rend:<\/unique> Basic attacks deal 10 bonus true damage to monsters.<br><br><i><i>(Unique Passives or Actives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_2003": "<consumable>Click to Consume:<\/consumable> Restores 150 Health over 15 seconds.",
	"game_item_description_2004": "<consumable>Click to Consume:<\/consumable> Restores 100 Mana over 15 seconds.",
	"game_item_description_2009": "<consumable>Click to Consume:<\/consumable> Restores 80 Health and 50 Mana over 10 seconds.",
	"game_item_description_2037": "<consumable>Click to Consume:<\/consumable> Grants 120-235 Health, based on champion level, and 15 Attack Damage for 3 minutes.",
	"game_item_description_2038": "<consumable>Click to Consume:<\/consumable> Grants 15-24% Attack Speed, based on champion level, and 8% Critical Strike Chance for 3 minutes.",
	"game_item_description_2039": "<consumable>Click to Consume:<\/consumable> Grants 25-40 Ability Power, based on champion level, and 10% Cooldown Reduction for 3 minutes.",
	"game_item_description_2040": "<consumable>Click to Consume:<\/consumable> Grants 20-42 Attack Damage based on champion level, 20-42% Attack Speed based on champion level, and 15% increased damage to Turrets for 4 minutes.",
	"game_item_description_2041": "<active>UNIQUE Active:<\/active> Consumes a charge to restore 120 health and 60 mana over 12 seconds.<br><unique>UNIQUE Passive:<\/unique> Starts with 3 charges and refills each time you stop by your shop.",
	"game_item_description_2042": "<consumable>Click to Consume:<\/consumable> Grants detection of nearby invisible units for up to 5 minutes or until your champion dies.",
	"game_item_description_2043": "<consumable>Click to Consume:<\/consumable> Places an invisible ward that reveals the surrounding area and invisible units in the area for 3 minutes.",
	"game_item_description_2044": "<consumable>Click to Consume:<\/consumable> Places an invisible ward that reveals the surrounding area for 3 minutes.",
	"game_item_description_2045": "<stats>+300 Health<\/stats><br><br><unique>UNIQUE Passive - Ward Refresh:<\/unique> Starts with 5 charges and refills each time you visit your shop.<br><active>UNIQUE Active - Ghost Ward:<\/active> Consumes a charge to place an invisible ward that reveals the surrounding area for 3 minutes. You may have a maximum of 3 wards placed from this item at once.",
	"game_item_description_2047": "<consumable>Click to Consume:<\/consumable> Grants detection of nearby invisible units for up to 5 minutes or until your champion dies.",
	"game_item_description_2048": "<consumable>Click to Consume:<\/consumable> Grants 30-64 Ability Power based on champion level, 15% Cooldown Reduction, and a huge boost to mana and energy regeneration for 4 minutes.",
	"game_item_description_2049": "<stats>+100 Health<\/stats><br><br><unique>UNIQUE Passive - Ward Refresh:<\/unique> Starts with 4 charges and refills each time you visit your shop.<br><active>UNIQUE Active - Ghost Ward:<\/active> Consumes a charge to place an invisible ward that reveals the surrounding area for 3 minutes. You may have a maximum of 2 wards placed from this item at once.",
	"game_item_description_2050": "<consumable>Click to Consume:<\/consumable> Places an invisible ward that reveals the surrounding area for 60 seconds.",
	"game_item_description_3001": "<stats>+70 Ability Power<br>+45 Magic Resist<\/stats><br><br><aura>UNIQUE Aura:<\/aura> Reduces the Magic Resist of nearby enemies by 20.",
	"game_item_description_3003": "<stats>+250 Mana<br>+50 Ability Power<br>+10 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Insight:<\/unique> Gain Ability Power equal to 3% of your Maximum Mana.<br><unique>UNIQUE Passive - Mana Charge:<\/unique> Each time you cast a spell or spend Mana, you gain 5 maximum Mana <i><i>(3 second cooldown)<\/i><\/i>. Bonus caps at +750 Mana.<br><br>This item transforms once it reaches +750 Mana, gaining a powerful mana shield active.",
	"game_item_description_3004": "<stats>+250 Mana<br>+10 Attack Damage<br>+7 Mana Regen per 5 seconds <\/stats><br><br><unique>UNIQUE Passive - Awe:<\/unique> Gain Attack Damage equal to 2% of your maximum Mana.<br><unique>UNIQUE Passive - Mana Charge:<\/unique> Each time you attack, cast a spell or spend Mana, you gain 4 maximum Mana <i><i>(3 second cooldown)<\/i><\/i>. Bonus caps at +750 Mana.<br><br>Transforms into Muramana at 750 Bonus Mana.",
	"game_item_description_3005": "<stats>+45 Armor<br>+15% Critical Strike Chance<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Gain Attack Damage equal to 1.5% of your maximum Health.",
	"game_item_description_3006": "<stats> +20% Attack Speed<\/stats><br><br><unique>UNIQUE Passive - Enhanced Movement:<\/unique> +45 Movement Speed",
	"game_item_description_3009": "<unique>UNIQUE Passive - Enhanced Movement:<\/unique> +60 Movement Speed<br><unique>UNIQUE Passive - Slow Resist:<\/unique> Movement slowing effects are reduced by 25%.",
	"game_item_description_3010": "<stats>+200 Health<br>+300 Mana<\/stats><br><br><unique>UNIQUE Passive - Valor's Reward:<\/unique> On leveling up, restores 150 Health and 200 Mana over 8 seconds.<br><br><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_3020": "<stats>+15 Magic Penetration<\/stats><br><br><unique>UNIQUE Passive - Enhanced Movement:<\/unique> +45 Movement Speed",
	"game_item_description_3022": "<stats>+700 Health<br>+30 Attack Damage<\/stats><br><br><unique>UNIQUE Passive - Icy:<\/unique> Your basic attacks slow your target's Movement Speed by 40% for 1.5 seconds <i><i>(30% slow for ranged attacks)<\/i><\/i>.",
	"game_item_description_3023": "<stats>+50 Ability Power<br>+30 Magic Resistance<br>+5% Movement Speed<\/stats><br><br><active>UNIQUE Active - Hunt:<\/active> Summons up to 2 invulnerable ghosts for 6 seconds to seek the two nearest enemy champions.  If they touch an enemy champion, they slow his Movement Speed by 40% and reveal him for  2.5 seconds - 120 second cooldown.",
	"game_item_description_3024": "<stats>+300 Mana<br>+40 Armor<\/stats><br><br><unique>UNIQUE Passive:<\/unique> +15% Cooldown Reduction",
	"game_item_description_3025": "<stats>+40 Ability Power<br>+500 Mana<br>+60 Armor<br>+15% Cooldown Reduction  <\/stats><br><br><unique>UNIQUE Passive - Spellblade:<\/unique> After using an ability, your next basic attack deals bonus physical damage equal to 125% of your base Attack Damage to surrounding enemies and creates a field for 3 seconds that slows enemies inside by 35% - 2 second cooldown.",
	"game_item_description_3026": "<stats>+50 Armor<br>+30 Magic Resist<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Revives your champion upon death, restoring 30% of your Maximum Health and Mana - 5 minute cooldown.",
	"game_item_description_3027": "<stats>+450 Health<br>+450 Mana<br>+60 Ability Power<\/stats><br><br><passive>Passive:<\/passive> This item gains 20 Health, 20 Mana, and 2 Ability Power every minute, up to 10 times.<br><unique>UNIQUE Passive - Valor's Reward:<\/unique> On leveling up, restores 150 Health and 200 Mana over 8 seconds.",
	"game_item_description_3028": "<stats>+25 Magic Resist<br>+7 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Mana Font:<\/unique> Increases your Mana Regen by 1% per 1% Mana you are missing.<br><br><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_3031": "<stats>+70 Attack Damage<br>+25% Critical Strike Chance<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Your critical strikes now deal 250% damage instead of 200%.",
	"game_item_description_3035": "<stats>+40 Attack Damage<\/stats><br><br><unique>UNIQUE Passive:<\/unique> You ignore 35% of your opponent's armor.<br><br><i><i>(Armor Penetration allows you to deal more physical damage to high Armored targets.  % Armor Penetration is applied before Flat Armor Penetration when calculating damage.)<\/i><\/i>",
	"game_item_description_3037": "<aura>UNIQUE Aura - Mana Warp:<\/aura> Nearby allied champions gain 6 Mana Regen per 5 seconds.<br><br><i><i>(Unique Auras with the same name do not stack.)<\/i><\/i>",
	"game_item_description_3040": "<stats>+1000 Mana<br>+60 Ability Power<br>+10 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Insight:<\/unique> Gain Ability Power equal to 3% of your Maximum Mana.<br><active>UNIQUE Active - Mana Shield:<\/active> Drains 25% of your current mana to shield yourself for an equal amount for 3 seconds -120 second cooldown.",
	"game_item_description_3041": "<stats>+20 Ability Power  <\/stats><br><br><unique>UNIQUE Passive:<\/unique> Your champion gains 8 Ability Power per stack, receiving 2 stacks for a kill or 1 stack for an assist <i><i>(stacks up to 20)<\/i><\/i>. You lose a third of your stacks on death. At 20 stacks, your champion gains 15% Cooldown Reduction.",
	"game_item_description_3042": "<stats>+1000 Mana<br>+20 Attack Damage<br>+7 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Awe:<\/unique> Gain Attack Damage equal to 2% of your maximum Mana.<br>Toggle: Your single target spells and attacks consume 3% of your current mana to deal twice the amount as magic damage.",
	"game_item_description_3044": "<stats>+200 Health<br>+20 Attack Damage<\/stats><br><br><unique>UNIQUE Passive - Icy:<\/unique> Your basic attacks have a 25% chance to slow your target's Movement Speed by 30% for 2 seconds <i><i>(20% slow for ranged attacks)<\/i><\/i>.",
	"game_item_description_3046": "<stats>+50% Attack Speed<br>+30% Critical Strike Chance<br>+5% Movement Speed<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Your champion ignores unit collision.<br><br><i><i>(A unit ignoring unit collision may walk through all units unhindered.)<\/i><\/i>",
	"game_item_description_3047": "<stats>+25 Armor<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Blocks 10% of the damage from champion basic attacks.<br><unique>UNIQUE Passive - Enhanced Movement:<\/unique> +45 Movement Speed",
	"game_item_description_3050": "<stats>+250 Health<br>+15% Cooldown Reduction<\/stats><br><br><aura>UNIQUE Aura:<\/aura> Nearby allied champions gain 10% Life Steal and 20 Attack Damage.",
	"game_item_description_3056": "<stats>+350 Health<br>+300 Mana<br>+55 Armor<\/stats><br><br><active>UNIQUE Active:<\/active>  Prevents the closest enemy tower from attacking for 2.5 seconds - 120 second cooldown. This effect cannot be used against the same tower more than once every 7.5 seconds.",
	"game_item_description_3057": "<stats>+200 Mana<br>+25 Ability Power<\/stats><br><br><unique>UNIQUE Passive - Spellblade:<\/unique> After using an ability, your next basic attack deals bonus physical damage equal to your base Attack Damage - 2 second cooldown.<br><br><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_3060": "<stats>+50 Ability Power<br>+30 Armor<\/stats><br><br><aura>UNIQUE Aura - Valor:<\/aura> Nearby allies gain 10 Health Regen per 5 seconds and nearby allied minions deal 15% increased damage.<br><active>UNIQUE Active - Promote:<\/active> Transforms a nearby siege minion to a more powerful unit. You gain all the gold this unit earns - 180 second cooldown.",
	"game_item_description_3065": "<stats>+50 Magic Resist<br>+200 Health<br>+15% Cooldown Reduction<\/stats><br><br><unique>UNIQUE Passive:<\/unique> Increases your healing, regeneration and drain effects on yourself by 20%",
	"game_item_description_3067": "<stats>+200 Health  <\/stats><br><br><unique>UNIQUE Passive:<\/unique> +10% Cooldown Reduction",
	"game_item_description_3068": "<stats>+450 Health<br>+45 Armor  <\/stats><br><br><unique>UNIQUE Passive:<\/unique> Deals 40 magic damage per second to nearby enemies.",
	"game_item_description_3069": "<stats>+250 Health<br>+10 Health Regen per 5 seconds<br>+10 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive:<\/unique> +10% Cooldown Reduction<br><active>UNIQUE Active:<\/active> Nearby allies gain 40% Movement Speed for 3 seconds - 60 second cooldown.",
	"game_item_description_3070": "<stats>+250 Mana<br>+7 Mana Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Mana Charge:<\/unique> Each time you cast a spell or spend Mana, your maximum Mana increases by 4 <i><i>(3 second cooldown)<\/i><\/i>. Bonus caps at +750 Mana.<br><br><i><i>(Unique Passives with the same name don't stack.)<\/i><\/i>",
	"game_item_description_3071": "<stats>+250 Health<br>+50 Attack Damage<br>+10% Cooldown Reduction<br><br><\/stats><passive>UNIQUE Passive:<\/passive> +10 Armor Penetration<br><passive>Passive:<\/passive> Dealing physical damage to an enemy champion reduces their Armor by 6.25% for 4 seconds. This effect stacks up to 4 times (Maximum of 25% Armor Reduction).",
	"game_item_description_3072": "<stats>+70 Attack Damage<br>+12% Life Steal<\/stats><br><br><passive>Passive:<\/passive> Gains 1 stack per kill, up to a maximum of 30. Each stack grants +1 Attack Damage and +0.2% Life Steal <i><i>(max: +30 Attack Damage and +6% Life Steal)<\/i><\/i>. Half of the current stacks are lost upon death.",
	"game_item_description_3074": "<stats>+75 Attack Damage<br>+15 Health Regen per 5 seconds<br>+10% Life Steal<\/stats><br><br><passive>Passive:<\/passive> Damage dealt by this item works with Life Steal.<br><unique>UNIQUE Passive - Cleave:<\/unique> Your attacks deal up to 60% of your Attack Damage to units around your target - decaying down to 20% near the edge.<br><active>UNIQUE Active - Crescent:<\/active> Deals up to 100% of your Attack Damage to units around you - decaying down to 60% near the edge - 10 second cooldown.",
	"game_item_description_3075": "<stats>+100 Armor  <\/stats><br><br><unique>UNIQUE Passive:<\/unique> On being hit by basic attacks, returns 30% of damage taken as magic damage.",
	"game_item_description_3077": "<stats>+50 Attack Damage<br>+15 Health Regen per 5 seconds<\/stats><br><br><unique>UNIQUE Passive - Cleave:<\/unique> Your attacks deal up to 60% of your Attack Damage to units around your target - decaying down to 20% near the edge.<br><active>UNIQUE Active - Crescent:<\/active> Deals up to 100% of your Attack Damage to units around you - decaying down to 60% near the edge - 10 second cooldown.",
	"game_item_description_3078": "<stats>+30 Attack Damage<br>+30 Ability Power<br>+30% Attack Speed<br>+10% Critical Strike Chance<br>+8% Movement Speed<br>+250 Health<br>+200 Mana<\/stats><br><br><unique>UNIQUE Passive - Icy:<\/unique> Your basic attacks have a 25% chance to slow your target's Movement Speed by 30% for 2 seconds <i><i>(20% for ranged.)<\/i><\/i><br><unique>UNIQUE Passive - Spellblade:<\/unique> After using an ability, your next basic attack deals bonus physical damage equal to 150% of your base Attack Damage <i><i>(2 second cooldown)<\/i><\/i>.",
	"game_item_description_3082": "<stats>+50 Armor<\/stats><br><br><unique>UNIQUE Passive - Cold Steel:<\/unique> If you are hit by a basic attack, you slow the attacker's Attack Speed by 20% 

;
